services:
  - type: web
    name: moneynotes-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn tracker.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
